name: Kanban Discord Notifications

on:
  project_v2_item:
    types: [created, edited, deleted]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Wysylanie powiadomienia
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "Użytkownik `${{ github.actor }}` dokonał zmiany (akcja: `${{ github.event.action }}`) w projekcie.",
            "username": "GitHub Kanban Bot"
          }' \
          $DISCORD_WEBHOOK
